# Alphabets that translate letters to aeronautical letters

DIC_LETTERS_EN = {
  "A": "Alpha",
  "B": "Bravo",
  "C": "Charlie",
  "D": "Delta",
  "E": "Echo", 
  "F": "Foxtrot", 
  "G": "Golf",
  "H": "Hotel",
  "I": "India", 
  "J": "Juliett",  
  "K": "Kilo",
  "L": "Lima",
  "M": "Mike",
  "N": "November", 
  "O": "Oscar",
  "P": "Papa",
  "Q": "Quebec",
  "R": "Romeo",
  "S": "Sierra",
  "T": "Tango",
  "U": "Uniform",
  "V": "Victor",
  "W": "Whiskey",
  "X": "X-ray",     
  "Y": "Yankee", 
  "Z": "Zoolu",
}

DIC_LETTERS_FR = {
  "A": "Alpha",
  "B": "Bravo",
  "C": "Charlie",
  "D": "Delta",
  "E": "éko", 
  "F": "Foxtrote", 
  "G": "Golf",
  "H": "Hotel",
  "I": "Inndia", 
  "J": "Juliaite",  
  "K": "Kilo",
  "L": "Lima",
  "M": "Maïque",
  "N": "Novem beur", 
  "O": "Oscar",
  "P": "Papa",
  "Q": "Québec",
  "R": "Romeo",
  "S": "Sierra",
  "T": "Tango",
  "U": "Uniforme",
  "V": "Victor",
  "W": "Ouisss ki",
  "X": "X-ray",     
  "Y": "Yénki", 
  "Z": "Zouulou",
}

#Note: For a more correct pronounciation in French, we modify the following words:
#Echo -> Et Ko ; India -> Inndia ; November -> Novem beur ; Yankee -> Yénki
DIC_TRAD_FR_EN=thisdict={
    "absolu":"absolute",
    "continu":"continuous",
    "relatif":"relative",
    "droite":"right",
    "gauche":"left",
    "fixe":"fixed",
    "montee":"climbing",
    "descente":"descending",
    "minimum":"minimum",
    "maximum":"maximum",
    "reduction":"decreasing",
    "augmentation":"increasing",
    "indiquee":"indicated",
    "indique":"indicated",
    "unité":"unit",
    "knot":"noeud",
    "knots":"noeuds",
    "mach":"mach",
}